# Generated by Django 3.1.12 on 2022-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_theme',
            field=models.ImageField(default='media/default.png', upload_to='media/kurs_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='media/default.png', upload_to='media/cat_images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
