# Generated by Django 3.1.12 on 2022-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('group', models.CharField(max_length=10)),
                ('lecture', models.CharField(max_length=5)),
                ('practic', models.CharField(max_length=5)),
                ('project', models.CharField(max_length=5)),
                ('visits', models.CharField(max_length=5)),
                ('score', models.CharField(max_length=5)),
            ],
        ),
    ]
